postcss.config.js

chore : tailwindcss 수정

---

src/components/RouteTabs.jsx
src/pages/Main.jsx

라우트탭 넣고 라우팅설정도 해놨습니다! 페이지 만드실 때 /api /erd /diagram 으로 경로 설정해주시면 될 것 같습니다

design : 라우트탭 퍼블리싱

---

src/assets/image/columnLine.svg
src/assets/image/rowLine.svg
src/components/Line.jsx
src/pages/Main.jsx

세로줄(columnLine)은 왼쪽 여백 300px(라우트탭고려), 화면 높이의 90%만큼 세로 길이를 잡고(사용자 화면 크기 고려) 수직 중앙 정렬 했습니다!
가로줄(rowLine)은 위쪽 여백 150px(Navbar고려), 화면 너비의 90%만큼 가로 길이를 잡고 (사용자 화면 크기 고려)수평 중앙 정렬했습니다!!

design : 분할 선 퍼블리싱

---

src/components/Line.jsx
src/components/Navbar.jsx
src/pages/Layout.jsx
src/pages/Main.jsx

navbar와 Line 합쳐서 Layout으로 만들고 children속성 넣어줬습니다 각 페이지에 layout import해서 사용하시면 됩니다!

[design/#31] layout 지정

---

src/App.jsx
src/pages/InputPage.jsx
src/pages/Layout.jsx

[design] 정보입력페이지 퍼블리싱

---

src/App.jsx
src/components/ChooseBox.jsx
src/pages/BackDatabase.jsx
src/pages/BackFramework.jsx
src/pages/FrontBuild.jsx
src/pages/FrontFramework.jsx
src/pages/FrontLanguage.jsx
src/pages/FrontPackage.jsx

[design/#62]중간수정2

---

src/App.jsx
src/pages/BackDatabase.jsx
src/pages/BackFramework.jsx
src/pages/FrontFramework.jsx
src/pages/SettingPage.jsx

[design/#67]중간수정

---

src/App.jsx
src/components/BackStep/BackStep.jsx
src/components/ChooseBox/ChooseBox.jsx
src/components/FrontStep/FrontStep.jsx
src/pages/BackDatabase.jsx
src/pages/BackFramework.jsx
src/pages/FrontBuild.jsx
src/pages/FrontFramework.jsx
src/pages/FrontLangauge.jsx
src/pages/FrontPackage.jsx
src/pages/SettingPage.jsx

#90 
> 각 페이지 경로에서 하이픈 제거
> BackStep, FrontStep 컴포넌트에서 진행단계를 나타내는 색 변경
> 각 페이지에서 Step 컴포넌트 너비 수정
>

[design/#90]페이지및 컴포넌트 퍼블리싱 수정

---

package.json
src/App.css
src/App.jsx
src/components/Background.jsx
src/components/Button/Button.jsx
src/components/EditModal.jsx
src/components/MultiViewBox/MultiViewBox.jsx
src/pages/Layout.jsx
src/pages/Specific.jsx
tailwind.config.js
yarn.lock

Design/#89 기능명세페이지 퍼블리싱

---

package.json
src/api/axios.config.js
yarn.lock

쿠키 인증 문제 해결

---

src/api/axios.config.js
src/api/reposApi.js
src/api/techStacksSetupApi.js
src/components/SettingModal/FrontSettingModal.jsx
src/pages/FrontSetting/FrontFramework.jsx
src/pages/FrontSetting/FrontLangauge.jsx
src/pages/SettingPage.jsx
src/store/useSettingStore.js

techStackSetupApi 수정해서 기능구현 완료했습니다!

[Feat/#103] 초기세팅 기능구현 완료

---

src/api/axios.config.js

modified:   src/api/axios.config.js

---

src/api/documentsApi.js
src/pages/DiagramPage.jsx
src/pages/ErdPage.jsx
src/pages/SwaggerPage.jsx

[feat/#134] 설계저장기능 연동 완료

---

src/api/documentsApi.js
src/pages/Specific.jsx

[feat/#134] fetch signal추가

---

src/api/documentsApi.js
src/components/EditModal.jsx
src/pages/Specific.jsx

[Feat/#134] sse기능 연동

---

src/pages/DiagramPage.jsx
src/pages/ErdPage.jsx
src/pages/SwaggerPage.jsx

#142 
- ERD, API, DIAGRAM 페이지에서 메인으로가기, 세팅하러가기 버튼 추가
>

[feat/#142]설계페이지 버튼 추가

---

src/api/reposApi.js
src/components/GitRepository.jsx
src/components/MyProject.jsx

#145 
>
> 도커인도커 연동 되는지 배포 서버에서 확인 필요

[feat/#145]도커인도커연동

---

package.json
src/components/GitRepository.jsx
src/components/SettingModal/BackSettingModal.jsx
src/components/SettingModal/FrontSettingModal.jsx
src/store/useSettingStore.js
yarn.lock

[feat/#147] 도커인도커 API 수정 및 로딩 추가

---

src/components/GitRepository.jsx

create -> push/ confirm -> test로 글자 변경
주의사항 글자 크기 변경
REPOSITRY 글자 가운데 정렬
>

[feat/#151] 디자인수정

---

src/components/GitRepository.jsx
src/store/useSettingStore.js

#153 
- 사이트 주소 기본값을 site로 설정
- test 버튼 눌렀을때 로딩창이 뜨게 수정
>

[feat/#153] 도커인도커 디자인 수정
